---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    #when: ansible_facts['os_family'] == "Debian"
    when: ansible_distribution == 'Ubuntu'

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    #when: ansible_facts['os_family'] == "Debian"
    when: ansible_distribution == 'Ubuntu'

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    #when: ansible_facts['os_family'] == "Debian"
    when: ansible_distribution == 'Ubuntu'

  - name: update repository index
    dnf:
      update_cache: yes
    #when: ansible_facts['os_family'] == "Fedora"
    when: ansible_distribution == 'Fedora'

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
    #when: ansible_facts['os_family'] == "Fedora"
    when: ansible_distribution == 'Feora'

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    #when: ansible_facts['os_family'] == "Fedora"
    when: ansible_distribution == 'Fedora'



